/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Timestamp;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.Date;
import java.util.ArrayList;
import java.sql.Connection;
import javax.swing.DefaultListModel;
/**
 *
 * @author wengw
 */
public class MainFrame extends javax.swing.JDialog {

    /**
     * Creates new form MainFrame
     */
    private DefaultListModel ReservationStatus;
    private DefaultListModel WaitlistStatus;
    private DefaultListModel FacultiesStatus;
    public MainFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        if (!Faculty.getFaculty().isEmpty())
        {
            FacultyBox();
        }
        DateBox();
        ReservationStatus = new DefaultListModel();
        ReservationStatusListByDate.setModel(ReservationStatus);
        ReservationStatus.removeAllElements();
        
        WaitlistStatus = new DefaultListModel();
        WaitingStatusList.setModel(WaitlistStatus);
        Waitlist();
        
        FacultiesStatus = new DefaultListModel();
        ReservationStatusListByFaculty.setModel(FacultiesStatus);
        FacultiesStatus.removeAllElements();
        Room();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrameTitle = new javax.swing.JLabel();
        JTabbedPane = new javax.swing.JTabbedPane();
        AddPanel = new javax.swing.JPanel();
        FacultyNameLabel = new javax.swing.JLabel();
        AddFacultyButton = new javax.swing.JButton();
        AddFacultyStatusLabel = new javax.swing.JLabel();
        AddFacultyTextField = new javax.swing.JTextField();
        AddDatePanel = new javax.swing.JPanel();
        AddDateLabel = new javax.swing.JLabel();
        AddDateTextField = new javax.swing.JTextField();
        AddDateButton = new javax.swing.JButton();
        DateStatusLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MakeReservationPanel = new javax.swing.JPanel();
        ReserveDateLabel = new javax.swing.JLabel();
        FacultyNamesBox = new javax.swing.JComboBox<>();
        ReserveFNameLabel = new javax.swing.JLabel();
        SeatsLabel = new javax.swing.JLabel();
        SeatsTextField = new javax.swing.JTextField();
        ReserveButton = new javax.swing.JButton();
        ReserveStatusLabel = new javax.swing.JLabel();
        ReserveDateBox = new javax.swing.JComboBox<>();
        ReserveResultStatusLabel = new javax.swing.JLabel();
        ReservationStatusPanel = new javax.swing.JPanel();
        DateJlabel = new javax.swing.JLabel();
        DateStatus = new javax.swing.JComboBox<>();
        getDateStatus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReservationStatusListByDate = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        FacultyStatus = new javax.swing.JComboBox<>();
        getFacultyStatus = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ReservationStatusListByFaculty = new javax.swing.JList<>();
        WaitingStatusPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        WaitingStatusList = new javax.swing.JList<>();
        AddRoomSeatsPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        AddRoomTextField = new javax.swing.JTextField();
        AddSeatsTextField = new javax.swing.JTextField();
        AddRoomSeatsButton = new javax.swing.JButton();
        AddRoomSeatsLabel = new javax.swing.JLabel();
        CancelDropPanel = new javax.swing.JPanel();
        CancelFacultyLabel = new javax.swing.JLabel();
        CancelDateLabel = new javax.swing.JLabel();
        CancelFacultyBox = new javax.swing.JComboBox<>();
        CancelDateBox = new javax.swing.JComboBox<>();
        DropRoomLabel = new javax.swing.JLabel();
        DropRoomBox = new javax.swing.JComboBox<>();
        CancelReserveButton = new javax.swing.JButton();
        CancelRoomButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CancelReservationLabel = new javax.swing.JLabel();
        CancelRoomLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FrameTitle.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        FrameTitle.setText("Room Scheduler");

        FacultyNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        FacultyNameLabel.setText("Faculty Name:");

        AddFacultyButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AddFacultyButton.setText("Add");
        AddFacultyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFacultyButtonActionPerformed(evt);
            }
        });

        AddFacultyStatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        AddFacultyTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout AddPanelLayout = new javax.swing.GroupLayout(AddPanel);
        AddPanel.setLayout(AddPanelLayout);
        AddPanelLayout.setHorizontalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddFacultyStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(AddPanelLayout.createSequentialGroup()
                        .addComponent(FacultyNameLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AddFacultyButton)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        AddPanelLayout.setVerticalGroup(
            AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(AddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFacultyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacultyNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddFacultyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddFacultyStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Add Faculty", AddPanel);

        AddDateLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AddDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddDateLabel.setText("Date:");

        AddDateButton.setText("Add");
        AddDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Format: YYYY-MM-DD");

        javax.swing.GroupLayout AddDatePanelLayout = new javax.swing.GroupLayout(AddDatePanel);
        AddDatePanel.setLayout(AddDatePanelLayout);
        AddDatePanelLayout.setHorizontalGroup(
            AddDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDatePanelLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addGroup(AddDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DateStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddDatePanelLayout.createSequentialGroup()
                        .addComponent(AddDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(AddDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AddDateTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addComponent(AddDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        AddDatePanelLayout.setVerticalGroup(
            AddDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddDatePanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddDatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addComponent(DateStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(206, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Add Date", AddDatePanel);

        ReserveDateLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ReserveDateLabel.setText("Reserve Date:");
        ReserveDateLabel.setMaximumSize(new java.awt.Dimension(82, 17));
        ReserveDateLabel.setMinimumSize(new java.awt.Dimension(82, 17));
        ReserveDateLabel.setPreferredSize(new java.awt.Dimension(82, 17));

        FacultyNamesBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        ReserveFNameLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ReserveFNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ReserveFNameLabel.setText("Faculty:");
        ReserveFNameLabel.setMaximumSize(new java.awt.Dimension(82, 17));
        ReserveFNameLabel.setMinimumSize(new java.awt.Dimension(82, 17));
        ReserveFNameLabel.setPreferredSize(new java.awt.Dimension(82, 17));

        SeatsLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        SeatsLabel.setText("Total Seats:");
        SeatsLabel.setMaximumSize(new java.awt.Dimension(82, 17));
        SeatsLabel.setMinimumSize(new java.awt.Dimension(82, 17));
        SeatsLabel.setPreferredSize(new java.awt.Dimension(82, 17));

        SeatsTextField.setColumns(5);
        SeatsTextField.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SeatsTextField.setPreferredSize(new java.awt.Dimension(94, 23));

        ReserveButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ReserveButton.setText("Reserve");
        ReserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveButtonActionPerformed(evt);
            }
        });

        ReserveStatusLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        ReserveDateBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        ReserveResultStatusLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout MakeReservationPanelLayout = new javax.swing.GroupLayout(MakeReservationPanel);
        MakeReservationPanel.setLayout(MakeReservationPanelLayout);
        MakeReservationPanelLayout.setHorizontalGroup(
            MakeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeReservationPanelLayout.createSequentialGroup()
                .addGroup(MakeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MakeReservationPanelLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(MakeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MakeReservationPanelLayout.createSequentialGroup()
                                .addComponent(FacultyNamesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(ReserveDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReserveDateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(MakeReservationPanelLayout.createSequentialGroup()
                                .addComponent(ReserveStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)))
                        .addComponent(SeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(ReserveButton))
                    .addGroup(MakeReservationPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ReserveResultStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(MakeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MakeReservationPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(ReserveFNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(776, Short.MAX_VALUE)))
        );
        MakeReservationPanelLayout.setVerticalGroup(
            MakeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MakeReservationPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(MakeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FacultyNamesBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReserveDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReserveDateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReserveStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(ReserveResultStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(MakeReservationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MakeReservationPanelLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(ReserveFNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(367, Short.MAX_VALUE)))
        );

        ReserveDateLabel.getAccessibleContext().setAccessibleName("Faculty:");

        JTabbedPane.addTab("Make Reservation", MakeReservationPanel);

        DateJlabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DateJlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DateJlabel.setText("Date:");

        DateStatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        getDateStatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getDateStatus.setText("Status");
        getDateStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDateStatusActionPerformed(evt);
            }
        });

        ReservationStatusListByDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane1.setViewportView(ReservationStatusListByDate);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Faculty:");

        FacultyStatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        getFacultyStatus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        getFacultyStatus.setText("Status");
        getFacultyStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getFacultyStatusActionPerformed(evt);
            }
        });

        ReservationStatusListByFaculty.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jScrollPane3.setViewportView(ReservationStatusListByFaculty);

        javax.swing.GroupLayout ReservationStatusPanelLayout = new javax.swing.GroupLayout(ReservationStatusPanel);
        ReservationStatusPanel.setLayout(ReservationStatusPanelLayout);
        ReservationStatusPanelLayout.setHorizontalGroup(
            ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationStatusPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ReservationStatusPanelLayout.createSequentialGroup()
                        .addComponent(DateJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(DateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(getDateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120)
                .addGroup(ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ReservationStatusPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(FacultyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(getFacultyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        ReservationStatusPanelLayout.setVerticalGroup(
            ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReservationStatusPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateJlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDateStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FacultyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getFacultyStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReservationStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Check Reservation Status", ReservationStatusPanel);

        jScrollPane2.setViewportView(WaitingStatusList);

        javax.swing.GroupLayout WaitingStatusPanelLayout = new javax.swing.GroupLayout(WaitingStatusPanel);
        WaitingStatusPanel.setLayout(WaitingStatusPanelLayout);
        WaitingStatusPanelLayout.setHorizontalGroup(
            WaitingStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitingStatusPanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(210, Short.MAX_VALUE))
        );
        WaitingStatusPanelLayout.setVerticalGroup(
            WaitingStatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitingStatusPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Check Waiting Status", WaitingStatusPanel);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Room:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("#Seats:");

        AddRoomSeatsButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        AddRoomSeatsButton.setText("Add");
        AddRoomSeatsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRoomSeatsButtonActionPerformed(evt);
            }
        });

        AddRoomSeatsLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout AddRoomSeatsPanelLayout = new javax.swing.GroupLayout(AddRoomSeatsPanel);
        AddRoomSeatsPanel.setLayout(AddRoomSeatsPanelLayout);
        AddRoomSeatsPanelLayout.setHorizontalGroup(
            AddRoomSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRoomSeatsPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(AddRoomSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddRoomSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AddRoomSeatsPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AddRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(AddRoomSeatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        AddRoomSeatsPanelLayout.setVerticalGroup(
            AddRoomSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddRoomSeatsPanelLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(AddRoomSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddRoomTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddRoomSeatsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(AddRoomSeatsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Add Room/#Seats", AddRoomSeatsPanel);

        CancelFacultyLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CancelFacultyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelFacultyLabel.setText("Faculty:");

        CancelDateLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CancelDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CancelDateLabel.setText("Date:");

        CancelFacultyBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        CancelDateBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        DropRoomLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        DropRoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DropRoomLabel.setText("Room:");

        DropRoomBox.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        CancelReserveButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CancelReserveButton.setText("Cancel");
        CancelReserveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelReserveButtonActionPerformed(evt);
            }
        });

        CancelRoomButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        CancelRoomButton.setText("Cancel");
        CancelRoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelRoomButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Cancel Reservation:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Cancel Room:");

        CancelReservationLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        CancelRoomLabel.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout CancelDropPanelLayout = new javax.swing.GroupLayout(CancelDropPanel);
        CancelDropPanel.setLayout(CancelDropPanelLayout);
        CancelDropPanelLayout.setHorizontalGroup(
            CancelDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelDropPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(CancelDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CancelDropPanelLayout.createSequentialGroup()
                        .addGroup(CancelDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DropRoomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CancelFacultyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CancelDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CancelFacultyBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DropRoomBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64)
                        .addGroup(CancelDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CancelDropPanelLayout.createSequentialGroup()
                                .addComponent(CancelDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CancelDateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(CancelReserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CancelRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelReservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelRoomLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        CancelDropPanelLayout.setVerticalGroup(
            CancelDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CancelDropPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(CancelDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelFacultyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelFacultyBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelDateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(CancelDateBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelReserveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelReservationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(CancelDropPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DropRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DropRoomBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CancelRoomButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CancelRoomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        JTabbedPane.addTab("Cancel Reservation/Drop Room", CancelDropPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FrameTitle)
                .addGap(286, 286, 286))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(FrameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void AddFacultyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFacultyButtonActionPerformed
        // TODO add your handling code here:
        String fname = AddFacultyTextField.getText();
        if(Faculty.addFaculty(AddFacultyTextField.getText()))
        {
            AddFacultyStatusLabel.setText("Faculty: " + fname + " Added Successfully!");
            AddFacultyTextField.setText(" ");
        } else {
            AddFacultyStatusLabel.setText("Adding Faculty: " + fname + " Unsuccessfully, Please Try Again!");
        }
        FacultyBox();
    }//GEN-LAST:event_AddFacultyButtonActionPerformed

    private void ReserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveButtonActionPerformed
        // TODO add your handling code here:
        String Faculty = FacultyNamesBox.getSelectedItem().toString();
        Date date = Date.valueOf(ReserveDateBox.getSelectedItem().toString());
        int seats = Integer.parseInt(SeatsTextField.getText());
        boolean result = Reservations.addReservationEntry(Faculty, date, seats);
        ReserveResultStatusLabel.setText("Reserved successfully by " + Faculty + " for date: " + date + " with seats of " + seats);
        if (result == false)
        {
            Waitlist.addWaitlistEntry(Faculty, date, seats);
            ReserveResultStatusLabel.setText("Waitlist added for" + Faculty + " for date: " + date + " with seats of " + seats);
            Waitlist();
        }
    }//GEN-LAST:event_ReserveButtonActionPerformed

    private void getDateStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDateStatusActionPerformed
        // TODO add your handling code here:
        Date date = Date.valueOf(DateStatus.getSelectedItem().toString());
        ArrayList<ReservationEntry> reservations = Reservations.getReservationsByDate(date);
        ReservationStatus.removeAllElements();
        for (int count = 0; count < reservations.size(); count++)
        {
            ReservationStatus.addElement("Date: " +reservations.get(count).getDate() + " " + "Room: " + reservations.get(count).getRoom() + " " + "Faculty: " + reservations.get(count).getFaculty());
        }
        
    }//GEN-LAST:event_getDateStatusActionPerformed

    private void getFacultyStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getFacultyStatusActionPerformed
        // TODO add your handling code here:
        String Faculty = FacultyStatus.getSelectedItem().toString();
        ArrayList<ReservationEntry> reservations = Reservations.getReservationsByFaculty(Faculty);
        FacultiesStatus.removeAllElements();
        
        for (int count = 0; count < reservations.size(); count++)
        {
            FacultiesStatus.addElement("Date: " + reservations.get(count).getDate() + " " + "Room: " + reservations.get(count).getRoom());
        }
        
    }//GEN-LAST:event_getFacultyStatusActionPerformed

    private void AddRoomSeatsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRoomSeatsButtonActionPerformed
        // TODO add your handling code here:
        String room = AddRoomTextField.getText();
        int seats = Integer.parseInt(AddSeatsTextField.getText());
        Rooms.addRoom(room, seats);
        ArrayList<WaitlistEntry> waitlist = Waitlist.getWaitlists();
        AddRoomSeatsLabel.setText("Room added successfully with room name: " + room + " seats of " + seats);
        for (int count = 0; count < waitlist.size(); count++)
        {
            String Faculty = waitlist.get(count).getFaculty();
            Date date = waitlist.get(count).getDate();
            seats = waitlist.get(count).getSeats();
            boolean result = Reservations.addReservationEntry(Faculty, date, seats);
            if (result)
            {
                Waitlist.deleteWaitlistEntry(Faculty, date);
                Waitlist();
                AddRoomSeatsLabel.setText("This room now been reserve by a faculty member!");
            }
        }
        Room();
    }//GEN-LAST:event_AddRoomSeatsButtonActionPerformed

    private void AddDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateButtonActionPerformed
        // TODO add your handling code here:
        Date date = Date.valueOf(AddDateTextField.getText());
        Dates.addDate(date);
        DateStatusLabel.setText("Date: " + date + " added successfully!");
        DateBox();
    }//GEN-LAST:event_AddDateButtonActionPerformed

    private void CancelReserveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelReserveButtonActionPerformed
        // TODO add your handling code here:
        String Faculty = String.valueOf(CancelFacultyBox.getSelectedItem().toString());
        Date date = Date.valueOf(CancelDateBox.getSelectedItem().toString());
        Reservations.cancelReservation(Faculty, date);
        Waitlist.cancelWaitlistEntry(Faculty, date);
        Waitlist();
        CancelReservationLabel.setText("Reservation cancelled successfully!");
        ArrayList<WaitlistEntry> waitlist = Waitlist.getWaitlists();
        
        for (int count = 0; count < waitlist.size(); count++)
        {
            Faculty = waitlist.get(count).getFaculty();
            date = waitlist.get(count).getDate();
            int seats = waitlist.get(count).getSeats();
            boolean result = Reservations.addReservationEntry(Faculty, date, seats);
            if (result)
            {
                Waitlist.deleteWaitlistEntry(Faculty, date);
                CancelReservationLabel.setText("This room now been reserve by a faculty member!");
                Waitlist();
            }
        }
    }//GEN-LAST:event_CancelReserveButtonActionPerformed

    private void CancelRoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelRoomButtonActionPerformed
        // TODO add your handling code here:
        boolean removed = false;
        String roomName = DropRoomBox.getSelectedItem().toString();
        Reservations reserve = new Reservations();
        ArrayList<ReservationEntry> rooms = reserve.getReservedRoomInfo();
        ArrayList<ReservationEntry> waitlist = new ArrayList<>();
        for (int count = 0; count < rooms.size(); count++)
        {
            if(rooms.get(count).getRoom().equals(roomName))
            {
                String Faculty = rooms.get(count).getFaculty();
                String Room = rooms.get(count).getRoom();
                Date date = rooms.get(count).getDate();
                int seats = rooms.get(count).getSeats();
                Timestamp timestamp = rooms.get(count).getTimestamp();
                
                ReservationEntry waitlists = new ReservationEntry(Faculty, Room, date, seats, timestamp);
                waitlist.add(waitlists);
                
            }
        }
        Rooms.cancelRoom(roomName);
        Reservations.deleteReservation(roomName);
        CancelRoomLabel.setText("Room: " + roomName + " cancelled successfully!");
        for (int count = 0; count < waitlist.size(); count++)
        {
            String Faculty = waitlist.get(count).getFaculty();
            Date date = waitlist.get(count).getDate();
            int seats = waitlist.get(count).getSeats();
            boolean result = Reservations.addReservationEntry(Faculty, date, seats);
            if (result)
            {
                removed = true;
                Waitlist.deleteWaitlistEntry(Faculty, date);
                CancelRoomLabel.setText("This room now been reserved by a faculty member!");
                Waitlist();
            }
            else
            {
                Waitlist.addWaitlistEntry(Faculty, date, seats);
                Waitlist();
            }
        }
        if (removed == false)
        {
            CancelRoomLabel.setText("No room(s) can be reserve at the moment, waitlist updated");
        }
        Waitlist();
    }//GEN-LAST:event_CancelRoomButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainFrame dialog = new MainFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDateButton;
    private javax.swing.JLabel AddDateLabel;
    private javax.swing.JPanel AddDatePanel;
    private javax.swing.JTextField AddDateTextField;
    private javax.swing.JButton AddFacultyButton;
    private javax.swing.JLabel AddFacultyStatusLabel;
    private javax.swing.JTextField AddFacultyTextField;
    private javax.swing.JPanel AddPanel;
    private javax.swing.JButton AddRoomSeatsButton;
    private javax.swing.JLabel AddRoomSeatsLabel;
    private javax.swing.JPanel AddRoomSeatsPanel;
    private javax.swing.JTextField AddRoomTextField;
    private javax.swing.JTextField AddSeatsTextField;
    private javax.swing.JComboBox<String> CancelDateBox;
    private javax.swing.JLabel CancelDateLabel;
    private javax.swing.JPanel CancelDropPanel;
    private javax.swing.JComboBox<String> CancelFacultyBox;
    private javax.swing.JLabel CancelFacultyLabel;
    private javax.swing.JLabel CancelReservationLabel;
    private javax.swing.JButton CancelReserveButton;
    private javax.swing.JButton CancelRoomButton;
    private javax.swing.JLabel CancelRoomLabel;
    private javax.swing.JLabel DateJlabel;
    private javax.swing.JComboBox<String> DateStatus;
    private javax.swing.JLabel DateStatusLabel;
    private javax.swing.JComboBox<String> DropRoomBox;
    private javax.swing.JLabel DropRoomLabel;
    private javax.swing.JLabel FacultyNameLabel;
    private javax.swing.JComboBox<String> FacultyNamesBox;
    private javax.swing.JComboBox<String> FacultyStatus;
    private javax.swing.JLabel FrameTitle;
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JPanel MakeReservationPanel;
    private javax.swing.JList<String> ReservationStatusListByDate;
    private javax.swing.JList<String> ReservationStatusListByFaculty;
    private javax.swing.JPanel ReservationStatusPanel;
    private javax.swing.JButton ReserveButton;
    private javax.swing.JComboBox<String> ReserveDateBox;
    private javax.swing.JLabel ReserveDateLabel;
    private javax.swing.JLabel ReserveFNameLabel;
    private javax.swing.JLabel ReserveResultStatusLabel;
    private javax.swing.JLabel ReserveStatusLabel;
    private javax.swing.JLabel SeatsLabel;
    private javax.swing.JTextField SeatsTextField;
    private javax.swing.JList<String> WaitingStatusList;
    private javax.swing.JPanel WaitingStatusPanel;
    private javax.swing.JButton getDateStatus;
    private javax.swing.JButton getFacultyStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void FacultyBox() {
        FacultyNamesBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFaculty().toArray()));
        FacultyStatus.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFaculty().toArray()));
        CancelFacultyBox.setModel(new javax.swing.DefaultComboBoxModel(Faculty.getFaculty().toArray()));
        CancelDate();
    }

    private void DateBox() {
        ReserveDateBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
        DateStatus.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
        CancelDateBox.setModel(new javax.swing.DefaultComboBoxModel(Dates.getDates().toArray()));
    }
    
    private void CancelDate() {
        ArrayList<Date> dates = new ArrayList<>();
        ArrayList<ReservationEntry> reservation = Reservations.getReservationsByFaculty(CancelFacultyBox.getSelectedItem().toString());
        for (int count = 0; count < reservation.size(); count++)
        {
            dates.add(reservation.get(count).getDate());
        }
        CancelDateBox.setModel(new javax.swing.DefaultComboBoxModel(dates.toArray()));
    }

    private void Waitlist() {
        ArrayList<WaitlistEntry> waitlist = Waitlist.getWaitlists();
        WaitlistStatus.removeAllElements();
        for(int count = 0; count < waitlist.size(); count++)
        {
            WaitlistStatus.addElement("Faculty: " + waitlist.get(count).getFaculty() + " " + "Date: " + waitlist.get(count).getDate() + " " + "Seats: " +waitlist.get(count).getSeats());
        }
    }

    private void Room() {
        ArrayList<String> room = new ArrayList<>();
        ArrayList<RoomEntry> rooms = Rooms.getRooms();
        for (int count = 0; count < rooms.size(); count++)
        {
            room.add(rooms.get(count).getName());
        }
        DropRoomBox.setModel(new javax.swing.DefaultComboBoxModel(room.toArray()));
    }
}
